### ISSUE TITLE
Cannot access file

### ISSUE THREAD

**Issue by kaciula** [theniceboy/security_scoped_resource#3]
Hi. When tapping on a file with a custom extension on iOS (that I registered as a type in Xcode), my Flutter app gets triggered and opened and I receive a file url such as this: `file:///private/var/mobile/Containers/Shared/AppGroup/1822654E-3DCE-480F-9C5E-BEF214FEAFC6/File%20Provider%20Storage/DAVIRW_240120_09-13-39.protern`

I'm calling you start method before trying to work with the file but I still get an error that the file does not exist. Any idea why?

**Comment by theniceboy** [comment]
Try this:

```dart
final path = Uri.decodeFull(pdfFile.path).replaceAll("file://", "");
final file = File(path);
```

**Comment by kaciula** [comment]
@theniceboy Thank you. It works now. Uri.decodeFull did the trick although I was already removing the "file://" part.

**Comment by theniceboy** [comment]
> @theniceboy Thank you. It works now. Uri.decodeFull did the trick although I was already removing the "file://" part.

No problem. `%20` is a url substitute for space.
